# -*- coding: utf-8 -*-
"""akonmodule

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTcJQgq4y5910Pi8aAId2PxOWXV8cQvE
"""

def cube(x):
  return x **3